name: lescase
favicon: null
layout_spectrum: 0.99911
typography_spectrum: 0.76068
title: LESCASE
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fd0000'
    - '#e9d100'
    - '#efad00'
    - '#f58100'
    - '#f85e00'
  brandStrength: 0.4662179958540946
  lightness: 0.375
  saturation: 0.5625
  rhythmicContrast: 0.75
purpose: []
